webtalk_init -webtalk_dir C:\\Anexos_PhD\\Vivado_project\\Project\\TE0745v18-Haptic\\Haptic_prj_18bits\\Haptic_prj.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2026-05-14 14:55:28" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "178060485_1777496732_210660895_142" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "10gj4hbtm3aqd4eo1gv0jn6rm3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_74" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "74" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3492 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.092 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1778766354615" -context "sdk\\\\hardware/1778766354615"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1778766354615"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1778766354615"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1778766354615"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1778766354615"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1778766354615"
webtalk_add_data -client sdk -key Device -value "7z045" -context "sdk\\\\hardware/1778766354615"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1778766354615"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1778766354615"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1778766354615"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1778766354615"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1778766928613"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1778766928613"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1778766928613"
webtalk_add_data -client sdk -key DebugCount -value "2" -context "sdk\\\\bsp/1778766928613"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1778766928613"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1778766928613"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1778766928613"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1778766928613"
webtalk_transmit -clientid 2927022517 -regid "178060485_1777496732_210660895_142" -xml C:\\Anexos_PhD\\Vivado_project\\Project\\TE0745v18-Haptic\\Haptic_prj_18bits\\Haptic_prj.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Anexos_PhD\\Vivado_project\\Project\\TE0745v18-Haptic\\Haptic_prj_18bits\\Haptic_prj.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Anexos_PhD\\Vivado_project\\Project\\TE0745v18-Haptic\\Haptic_prj_18bits\\Haptic_prj.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
